export type TypographyVariant =
  | "displayXLSerifRegular"
  | "displayLSerifRegular"
  | "displayMSerifRegular"
  | "displaySSerifRegular"
  | "displaySSansRegular"
  | "displaySSansSemiBold"
  | "pageHeaderSerifRegular"
  | "sectionHeaderSansMedium"
  | "subheadingSansMedium"
  | "subheadingSansRegular"
  | "paragraphSansMedium"
  | "paragraphSansRegular"
  | "labelSansRegular"
  | "labelSansMedium";
