import { LinkButton } from "./LinkButton";
import * as styles from "./styles.css";
import { StrictLocalMsg } from "@/utils/localization/StrictLocalMsg";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={styles.root}>
        <div style={{ display: "flex" }}>
          <LinkButton onChange={}>
            <StrictLocalMsg defaultMessage="Apply" />
          </LinkButton>
          <LinkButton href="/brands">Brands</LinkButton>
          <LinkButton href="/about">About</LinkButton>
        </div>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
