import { GetServerSideProps } from "next";
import Head from "next/head";

import { getPageData } from "../utils";

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const data = getPageData(req);
  return {
    props: {
      data,
    },
  };
};

const Home = ({ data }: { data: unknown }) => {
  void data;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello there 👋</h1>
        <p>How are ya?</p>
      </main>
    </>
  );
};

export default Home;
